#Should mana in GUIs be displayed with numbers?
numericalMana = false

[advanced-rendering]
	#If you turn this off, the special rendering is disabled for all machines and ignores the other config options
	all = true
	industrial-agglomeration-factory = true
	mechanical-daisy = true
	mechanical-brewery = true
	mechanical-mana-pool = true
	alfheim-market = true
	mechanical-apothecary = true
	mechanical-runic-altar = true

